In [1]:
%matplotlib inline
import os
import numpy as np
import scipy
import matplotlib.pyplot as plt

import vdmlab as vdm
from core import Rat, vdm_assign_label, combine_rats
from load_data import get_events
from plotting import plot_behavior

In [2]:
output_filepath = 'C:/Users/Emily/code/emi_biconditional/plots'

In [3]:
import info.check as check

In [ ]:
this_rat = '1'

rats = [this_rat]
data = dict()
data[this_rat] = Rat(this_rat)

sessions = [check]

for session in sessions:
    events = get_events(session.event_mat)
    
    rats_data = vdm_assign_label(events)

    data[this_rat].add_session(**rats_data)

n_sessions = len(data[this_rat].sessions)

df = combine_rats(data, rats, n_sessions)

In [ ]:
df.head()

In [ ]:
len(data['1'].sessions[0].trials)

In [4]:
events = get_events(check.event_mat)

In [5]:
events['cue_off'] - events['cue_on']

array([ 10.168483,  10.185226,  10.165625,  10.192707])

In [6]:
events['house_off'] - events['house_on']

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [9]:
events['house_on']

array([ 3508.984954,  4039.533407,  4394.89614 ,  5100.626425])

In [7]:
events['tone_off'] - events['tone_on']

array([ 10.004594,  10.000875,  10.001053,   9.999979])

In [8]:
events['noise_off'] - events['noise_on']

array([ 10.001054,  10.000007,  10.002231,  10.001205])

In [ ]:
events['1']

In [ ]:
events['cue_on']

In [ ]:
np.abs(events['cue_off'][1] - events['0'][1])

In [ ]:
np.abs(events['cue_off'][0] - events['0'][0])

In [ ]:
np.abs(events['house_on'][1] - events['2'][30])

In [ ]:
np.abs(events['house_on'][0] - events['2'][0])

In [ ]:
np.abs(events['tone_on'] - events['4'])

In [ ]:
np.abs(events['noise_on'] - events['3'])

In [ ]:
np.abs(events['tone_off'] - np.array(events['5'][1], events['5'][2]))

In [ ]:
np.abs(events['noise_off'] - np.array(events['5'][0], events['5'][3]))